version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of order
          - name: pdt_id
            description: id of product
          - name: revenue
            description: amount of product sold
          - name: quantity
            description: quantity of product sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez
        columns:
          - name: products_id
            description: id of product
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: price of each product
      - name: ship
        identifier: raw_gz_ship
        description: shipping costs of Greenweez
        columns:
          - name: orders_id
            description: id of orders
          - name: shipping_fee
            description: fee of a shipping
          - name: shipping_fee_1
            description: fee of a shipping_1
          - name: logCost
            description: cost of login
          - name: ship_cost
            description: cost of shipping
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords
        columns:
          - name: date_date
            description: date of the date
          - name: paid_source
            description: paid_source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: bing
        columns:
          - name: date_date
            description: date of the date
          - name: paid_source
            description: paid_source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click
        tests:
        - unique:
            column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo
        columns:
          - name: date_date
            description: date of the date
          - name: paid_source
            description: paid_source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click
        tests:
        - unique:
            column_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook
        columns:
          - name: date_date
            description: date of the date
          - name: paid_source
            description: paid_source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click
models:
  - name: int_campaigns
    description: data from all campaigns
    columns:
      - name: paid_source
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
  - name: finance_campaigns_day
    description: global kpi
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
        tests:
          - not_null
      - name: average_basket
        description: average basket cost for each day
        tests:
          - not_null
  - name: stg_stock
    columns:
      - name: model
        tests:
          - dbt_utils.not_empty_string