version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of order
          - name: pdt_id
            description: id of product
          - name: revenue
            description: amount of product sold
          - name: quantity
            description: quantity of product sold
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: product of Greenweez
        columns:
          - name: products_id
            description: id of product
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: price of each product
      - name: ship
        identifier: raw_gz_ship
        description: pshipping costs of Greenweez
        columns:
          - name: orders_id
            description: id of orders
          - name: shipping_fee
            description: fee of a shipping
          - name: shipping_fee_1
            description: fee of a shipping_1
          - name: logCost
            description: cost of login
          - name: ship_cost
            description: cost of shipping
